FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
WORKDIR /DDTV

COPY *.sh .

RUN chmod +x *.sh \
    && apk add --no-cache ffmpeg su-exec bash tzdata \
    && apk add libgdiplus --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted \
    && ./install.sh \
    && rm -rf /var/cache/apk/* /root/.cache /tmp/*

VOLUME /DDTV/Rec
EXPOSE 11419
ENTRYPOINT ["./start.sh"]
