FROM nginx:stable-alpine
ENV TZ=Asia/Shanghai
ENV PROXY_PASS=http://127.0.0.1:11419
COPY nginx/ /
# .sh file     in /docker-entrypoint.d
# 配置前端文件  in /usr/share/nginx/html
# default.conf in /etc/nginx/conf.d
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
