FROM nginx:stable-alpine
ENV TZ=Asia/Shanghai
ENV PROXY_PASS=http://DDTV.WEBServer:11419
COPY nginx/ /
  # .sh file     in /docker-entrypoint.d
  # 配置前端文件  in /DDTV/static
  # default.conf in /etc/nginx/conf.d

RUN apk add --no-cache bash\
    && rm -rf /var/cache/apk/* /root/.cache /tmp/* \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
