FROM nginx:stable-alpine
ENV TZ=Asia/Shanghai
COPY nginx/ /
# .sh file     in /docker-entrypoint.d
# .html file   in /usr/share/nginx/html
# default.conf in /etc/nginx/conf.d
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
