name: DDTV_Test

on:
  workflow_dispatch:
  push:
    branches: 
      - test

env:
  images: debug

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
                    echo "${{ env.images != debug }}"
