name: DDTV_Test

on:
  workflow_dispatch:
  push:
    branches: 
      - test

env:
  images: debug

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'test'
      - name: Metadata for images
        id: metadata
        uses: ./.github/workflows/test.yml
        with:
          test: test
