name: DDTV_Test

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      a.output1: ${{ steps.set-output.outputs.output1 }}
    steps:
      - id: set-output
        run: |
                    echo ::set-output name=output1::'Hello World'
  job2:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: |
                    echo Output1: ${{ needs.test.outputs.a.output1 }}
