name: test

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Output Version
        id: version
        run: |
          echo ${{ secrets.DOCKERHUB_USERNAME }}
          echo ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
