on:
  workflow_call:
    inputs:
      test:
        type: string
      t:
        type: string

jobs:
  Build_and_push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.test }}
          echo ${{ inputs.t }}
          echo fin
